### ISSUE TITLE
Temperature parsing  

### ISSUE THREAD

**Issue by luukvbaal** [zagortenay333/conky-Vision#23]
Temperature parsing seems to go wrong only for the maximum temperature of the following day. Any ideas what might cause this?
![image](https://user-images.githubusercontent.com/31730729/41847857-d4b135f2-787b-11e8-81f4-500a71e072ef.png)
Source: [https://openweathermap.org/city/2756253](url)
![image](https://user-images.githubusercontent.com/31730729/41847931-1b4dc1e2-787c-11e8-9060-91bb9971151a.png)
Thanks for the otherwise great config.

**Comment by zagortenay333** [comment]
Basically, with a free account you get the temp for every 3 hours of the next 5 days; you don't get the avg temp for any day. I just use the forecast for the first 3 hours of each day.

On their own website they don't have that limitation.

**Comment by zagortenay333** [comment]
Because the way the script that gets the weather works is trash...

As I said, I only get the max/min temp for the first 3 hours (midnight). The max temp from 00:00 to 03:00 is gonna be smaller than somewhere in the middle of day. I.e., max in the morning vs max overall.

I would just need to update the script to loop and find the max, but I'm too lazy right now; ain't nobody got time to deal with bash scripting...

**Comment by zagortenay333** [comment]
Mind you, there is still a chance that the forecast on their site will be different from the conky. Free accounts don't get the same info.
